CREATE DATABASE UNOAUNOALTERNATIVA
GO

USE UNOAUNOALTERNATIVA
GO

CREATE TABLE CLIENTES
(
	IDCLIENTE INT NOT NULL,
	DNI BIGINT NOT NULL,
	NOMBRE NVARCHAR(100) NOT NULL,
	APELLIDO NVARCHAR(100) NOT NULL,
)

CREATE TABLE CONTACTO_CLIENTES
(
	ID INT NOT NULL,
	NROTELEFONO NVARCHAR(50) NOT NULL,
	DIRECCION NVARCHAR NOT NULL,
	EMAIL NVARCHAR(100) NULL,
	CP INT NOT NULL,
)


ALTER TABLE CLIENTES
ADD CONSTRAINT PK_IDCLIENT PRIMARY KEY(IDCLIENTE)

ALTER TABLE CLIENTES
ADD CONSTRAINT U_DNI UNIQUE(DNI)

ALTER TABLE CLIENTES
ADD CONSTRAINT CK_DNI CHECK(DNI>0)


ALTER TABLE CONTACTO_CLIENTES
ADD CONSTRAINT FK_IDCLIENTE FOREIGN KEY (ID) REFERENCES CLIENTES(IDCLIENTE)

ALTER TABLE CONTACTO_CLIENTES
ADD CONSTRAINT PK_ID PRIMARY KEY (ID)
