CREATE DATABASE UNOaN
GO

USE UNOaN
GO

CREATE TABLE MARCAS
(
	IDMARCA BIGINT NOT NULL,
	NOMBRE NVARCHAR(30) NOT NULL,
	PRIMARY KEY (IDMARCA),

)
GO

ALTER TABLE MARCAS
ADD CONSTRAINT CHK_IDMARCA  CHECK(IDMARCA>0)

CREATE TABLE PRODUCTOS
(
	ID BIGINT NOT NULL IDENTITY (1,1),
	MARCA BIGINT NOT NULL FOREIGN KEY REFERENCES MARCAS(IDMARCA),
	CATEGORIA VARCHAR(30) NOT NULL,
	NOMBRE VARCHAR(30) NOT NULL,
	PRIMARY KEY(ID),
	
)
GO